### ISSUE TITLE
Setup GitHub Actions pipeline to build and publish package to NPM

### ISSUE THREAD

**Issue by BernhardHuberPlanBGmbH** [PlanBGmbH/flinkey-web-components#1]
In the further process of development we need to add a GitHub Actions pipeline that:
- builds our Web Components
- tests our Web Components (unit & e2e tests)
- publishes the updated Web Components to NPM

**Comment by aaronczichon** [comment]
Let me know if you need support on Github Actions.

**Comment by aaronczichon** [comment]
@TimoFrei and I added basic Github workflow to validate integrity into the project. See PR #https://github.com/PlanBGmbH/flinkey-web-components/pull/23.

NPM publishing will be added later.

**Comment by BernhardHuberPlanBGmbH** [comment]
@aaronczichon May the information regarding NPM publishing could be found at: [Publishing packages to the NPM registry](https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)

**Comment by aaronczichon** [comment]
Yeah I know but that's only one side of the medal. Also should automatically update/check package version and update it in package.json and on NPM.

**Comment by BernhardHuberPlanBGmbH** [comment]
@aaronczichon  Not sure, but seems to work [flinkey Web Components on NPM](https://www.npmjs.com/package/@planbgmbh/flinkey-web-components)

**Comment by aaronczichon** [comment]
I added a comment to the PR.
