### ISSUE TITLE
What Web Components should we create for MVP?

### ISSUE THREAD

**Issue by BernhardHuberPlanBGmbH** [PlanBGmbH/flinkey-web-components#2]
We should do a brainstorming regarding which Web Components to create first.

**Comment by BernhardHuberPlanBGmbH** [comment]
@ChristophBo May add your ideas here in conversation.

**Comment by ChristophBo** [comment]
Install product into car
Unistall product from car

Pair Service with product
Unlink Service from product

Show Keyfob-Catalog (Using Public API)

**Comment by BernhardHuberPlanBGmbH** [comment]
@ChristophBo When will public Keyfob API be available on production environment?

**Comment by ChristophBo** [comment]
@BernhardHuberPlanBGmbH Should be in progress and available the next days.

**Comment by BernhardHuberPlanBGmbH** [comment]
Closed
