### ISSUE TITLE
What's the best way for us to create the Web Components?

### ISSUE THREAD

**Issue by BernhardHuberPlanBGmbH** [PlanBGmbH/flinkey-web-components#4]
Decide what's the best way for us to create the Web Components.

**Comment by aaronczichon** [comment]
If you want to build them with the benefits of Typescript I would suggest [Stencil](https://stenciljs.com/) as web components compiler.

**Comment by BernhardHuberPlanBGmbH** [comment]
Why would you recommend Stencil instead of Svelte? Svelte supports TypeScript as well. So what are the benefits of Stencil over Svelte?

**Comment by BernhardHuberPlanBGmbH** [comment]
What makes Stencil more convenient for me over Svelte is all the built-in tooling they provide.

**Comment by BernhardHuberPlanBGmbH** [comment]
Duplicate of #3
